### ISSUE TITLE
inkscape not working on unraid server

### ISSUE THREAD

**Issue by jinx17** [accetto/headless-drawing-g3#2]
Hi,
using Unraid.
Installed via apps, setup ports, and docker is started OK. I can login to VNC session and I get XFCE desktop OK.
Trying to run Inkscape I get no response and application does not start.
When I run Version sticker I get:
Wait...
FEATURES_BUILD_SLIM_INKSCAPE=1
FEATURES_BUILD_SLIM_NOVNC=1
FEATURES_BUILD_SLIM_TOOLS=1
FEATURES_BUILD_SLIM_XFCE=1
FEATURES_BUILD_SLIM_XSERVER=1
FEATURES_INKSCAPE=1
FEATURES_NOVNC=1
FEATURES_SCREENSHOOTING=1
FEATURES_THUMBNAILING=1
FEATURES_USER_GROUP_OVERRIDE=
FEATURES_VERSION_STICKER=1
FEATURES_VNC=1
gpg 2.2.19
jq 1.6
Mousepad 0.4.2
nano 4.8
noVNC 1.2.0
Ristretto 0.10.0
Screenshooter 1.9.7
TigerVNC 1.11.0
Ubuntu 20.04.3
websockify 0.9.0
Press ENTER...

I also tried inkscape docker container (without ubuntu...), which works OK, but is outdated.
Best regards.

**Comment by accetto** [comment]
Hello,

thank you for reporting the issue. However, I'm not able to reproduce it.

I've just tested the Inkscape images and they're working just fine. However, I'm not using Unraid.

Why do you think they're outdated? The version 1.1.1 should be the current one.

```bash
Wait...
FEATURES_BUILD_SLIM_INKSCAPE=1
FEATURES_BUILD_SLIM_NOVNC=1
FEATURES_BUILD_SLIM_TOOLS=1
FEATURES_BUILD_SLIM_XFCE=1
FEATURES_BUILD_SLIM_XSERVER=1
FEATURES_INKSCAPE=1
FEATURES_NOVNC=1
FEATURES_SCREENSHOOTING=1
FEATURES_THUMBNAILING=1
FEATURES_USER_GROUP_OVERRIDE=
FEATURES_VERSION_STICKER=1
FEATURES_VNC=1
gpg 2.2.19
Inkscape 1.1.1
jq 1.6
Mousepad 0.4.2
nano 4.8
noVNC 1.2.0
Ristretto 0.10.0
Screenshooter 1.9.7
TigerVNC 1.11.0
Ubuntu 20.04.3
websockify 0.9.0
Press ENTER...
```

What I've noticed, there is the following line missing in your comment: `Inkscape 1.1.1`.

Could it be simply a copy-and-paste error? 

If not, than it would mean, that **Inkscape** really failed to start in that particular container.

Can you try to start it interactively and post me what it says? Just type `inkscape` in a terminal window inside the container.

You can also get debug info by using `inkscape --debug-info`. You can get more help by typing `inkscape --help` and also try some other switches.

Please let me know what have you get.

Regards,
accetto

**Comment by jinx17** [comment]
Hi Accetto,
thanks for your reply.
I tried running `inkscape --debug-info` in terminal, and this is what I get:
```
Wrong __data_start/_end pair
Aborted
```
I then tried also ` $ _INKSCAPE_GC=disable inkscape -V`
and I got response  `Inkscape 1.1.1 (1:1.1+202109281949+c3084ef5ed)`

About outdated. I refered outdated inkscape to another docker container, which runs without underlying OS (not your docker :) So this was just an info that inkscape does work on another docker container.

Regards,
Jinx

**Comment by jinx17** [comment]
Update:
when I run this command: `$ _INKSCAPE_GC=disable inkscape`, it openes inkscape and **it is working** (same command as above, but without -V)!

On terminal I can observe this:
```
Shortcut::read: invalid verb: DialogSpellcheck
Canvas::on_idle: clean region is empty!

** (org.inkscape.Inkscape:873): CRITICAL **: 19:13:18.160: void Inkscape::GC::Anchored::release() const: assertion '_anchor' failed

```

**Comment by jinx17** [comment]
Update2:
I ran also with debug-info, and got this:
```
$ _INKSCAPE_GC=disable inkscape --debug-info
Inkscape 1.1.1 (1:1.1+202109281949+c3084ef5ed)

    GLib version:     2.64.6
    GTK version:      3.24.20
    glibmm version:   2.64.2
    gtkmm version:    3.24.2
    libxml2 version:  2.9.10
    libxslt version:  1.1.34
    Cairo version:    1.16.0
    Pango version:    1.44.7
    HarfBuzz version: 2.6.4
    Poppler version:  0.86.1

    OS version:       Ubuntu 20.04.3 LTS

```

**Comment by accetto** [comment]
Thanks for the info. I didn't know about that switch (environment variable).

Do you think that it's required only on **Unraid** or should I add it into the image as a default?

**Comment by jinx17** [comment]
Sorry, I have NO IDEA, I am not a SW engineer / programmer. I just searched the internet and somehow got it working.
This is where I found it: https://gitlab.com/inkscape/inkscape/-/issues/1420
and this was someones comment 
_**Nathan Lee
Nathan Lee @nathanal · 1 year ago
Developer
@BilboMichal we had a related crash when packaging Inkscape as an appimage in Ubuntu 20.04 , the problem seems related to our use of libgc. Could you try disabling it to see if inkscape works in WSL (simply set the environmental variable _INKSCAPE_GC=disable, see #1458 (comment 356728737))**_

Based on this, using it like described could be a sollution, maybe.

**Comment by accetto** [comment]
Thanks. I've already tested it inside the container and it did do any harm, at least during the startup not. So I'll consider adding it to the images.

For now you can modify the desktop launcher or start **Inkscape** from the command line.

Or would you need an image with the switch already included?

Remark for SW folks: GC is about the garbage collector, so disabling it could influence how **Inkscape** behaves while using it. On the other hand, if the Inkscape developers recommend it, it should be OK.

**Comment by jinx17** [comment]
I would prefere adding it to the images :)
How can I edit Launcher for this to work?
Thanks.

**Comment by accetto** [comment]
I'm just about to publish new images. Which tag do you need as the first one?

**Comment by jinx17** [comment]
It doesn't matter. I am not in a hurry :)

**Comment by accetto** [comment]
So, the image `latest` is already there, the others will follow.

You can edit the launcher by right-clicking it and then `Edit Launcher` and the editing the content in the `Command` text box.
