### ISSUE TITLE
[Question] Add CUDA

### ISSUE THREAD

**Issue by Milor123** [accetto/headless-drawing-g3#7]
Bro, how can add CUDA to a image based in to your project, for example this https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-blender-g3

it works well but dont use my CUDA GPU, I have RTX 4070 but i am not sure about of how do it.

**Comment by accetto** [comment]
Hi, I'm sorry, but I cannot give any helpful answer to this question. This is not exactly my area and I also don't have an appropriate hardware for experiments. You can, of course, install any software using `sudo apt-get update && sudo apt-get -y install ...`, but this graphics related stuff has often special requirements, e.g. access permissions to the host's hardware. The first thing is to check, what the manufacturer says about usage from containers.
